# Site settings
title: うっかりぽん
description: Modern-Blog A Elegant template for Jekyll
keywords: 
author: しの
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://yuno0823.github.io/web2/" # the base hostname & protocol for your site
